name:                raupeka
version:             0.1.0.0
github:              "lillycat332/universe"
license:             BSD3
author:              "Lilly Cham"
maintainer:          "lilly@lillycat.tech"
copyright:           "2023 Lilly Cham"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lillycat332/universe/>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- megaparsec
- parser-combinators
- text
- bytestring
- containers
- mtl
- transformers
- lens
- unix
- deepseq

default-extensions:
- LambdaCase
- BlockArguments
- OverloadedStrings
- TypeApplications
- ImportQualifiedPost

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  raupeka-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raupeka

tests:
  raupeka-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raupeka
